config/routes.rb
Rails.application.routes.draw do
  #Ruta DELETE
  delete "/products/:id", to: "products#destroy"
  #Ruta PATCH
  patch "/products/:id", to: "products#update"
  #Ruta POST, metodo create, para guardar un nuevo producto en la BD
  post "products", to: "products#create"
  #Ruta GET, metodo new, as: es el metodo helper para no poner la ruta en nuestro codigo
  get "/products/new", to: "products#new", as: :new_product
  #Ruta GET, controlador products, metodo index, vista index, products_path()
  get "/products", to: "products#index"
  #Ruta GET con id, metodo show, as: :product para product_path()
  get "/products/:id", to: "products#show", as: :product
  #Ruta GET
  get "/products/:id/edit", to: "products#edit", as: :edit_product
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  #Validacion nivel de Aplicacion: que siempre este el valor
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    #pp @product

    if @product.save
      #redirect_to products_path
      #notice se metera en una variable llamada flash para estar disponible en la vista del path
      redirect_to products_path, notice: "Tu producto se ha creado correctamente"
    else
      #si no se salva, regresamos a la vista new con un status 422
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])

    if @product.update(product_params)
      redirect_to products_path, notice: "Tu producto se ha actualizado"
    else
      render :edit, status: :unprocessable_entity #422
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    #Por default rails manda un codigo 302, sobreescribimos con 303, indica redirect y no enlaza al producto eliminado
    redirect_to products_path, notice: "Tu producto se ha eliminado correctamente", status: :see_other #303
  end

  private

  def product_params
    params.require(:product).permit(:title, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vendelo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/flash" %>
    <%= render "shared/header" %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product do |form| %>
  <% @product.errors.full_messages.each do |error| %>
    <div>
      <%= error %>
    </div>
  <% end %>

  <div>
  <%= form.label :title %>
  <%= form.text_field :title %>
  </div>

  <div>
  <%= form.label :description %>
  <%= form.text_area :description %>
  </div>

  <div>
  <%= form.label :price %>
  <%= form.number_field :price %>
  </div>

  <%= form.submit %>
<% end %>

app/views/products/edit.html.erb
<h2>Editar producto</h2>

<%= render "form" %>

app/views/products/index.html.erb
<h1>Productos:</h1>

<% @products.each do |product| %>
  <%= link_to product_path(product.id), class: "product" do %>
  <%# link_to apuntando al path de productos, pasandole un id %>
    <h3><%= product.title %></h3>
    <h4><%= product.price%></h4>
  <% end %>
<% end %>

app/views/products/new.html.erb
<h2>Añadir producto</h2>

<%= render "form" %>

app/views/products/show.html.erb
<h2 class="title"><%= @product.title %></h2>

<h3 class="description"><%= @product.description %></h3>

<span class="price"><%= @product.price %></span>

<%= link_to "Editar producto", edit_product_path(@product) %>

<%# Ruta con turbo para el delete y una confirmacion %>
<%= link_to "Eliminar producto", product_path(@product), data: {
  turbo_method: :delete
  turbo_confirm: "¿Estas seguro?"
} %>

app/views/shared/_flash.html.erb
    <%# flash / flash.inspect%>
    <%= alert %>
    <%= notice %>

app/views/shared/_header.html.erb
<%= link_to products_path do %>
  <h1>Vendelo</h1>
<% end %>

<%= link_to "Añadir producto", new_product_path %>